### PR TITLE
Pull request for WAZO-3131-fix-cheroot-stop

### PR DESCRIPTION
**Pull request by fblackburn1**

### CODE REVIEW

**Review by sopelj — APPROVED** [review]

**Comment by sopelj** [comment]
recheck

**Comment by fblackburn1** [comment]
Not 100% about the fix/workaround pushed
since this PR reproduce this bug two time in a row, I want to check if the "fix" seem or not enough
I don't want necessary merge this commit inside this PR (or merge it at all)
but I'll engage discussion with pascal in https://github.com/wazo-platform/wazo-plugind/pull/64

**Comment by fblackburn1** [comment]
rebased to remove last try. gdebi is already called with `--non-interactive` option. But print some warning anyways .... :man_shrugging:

**Comment by fblackburn1** [comment]
auto-merge already approved

**Pull request merged**
